model_list:
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: ${DEEPSEEK_API_KEY}
      api_base: https://api.deepseek.com
  - model_name: deepseek-coder
    litellm_params:
      model: deepseek/deepseek-coder
      api_key: ${DEEPSEEK_API_KEY}
      api_base: https://api.deepseek.com
  - model_name: deepseek-reasoner
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_key: ${DEEPSEEK_API_KEY}
      api_base: https://api.deepseek.com

litellm_settings:
  drop_params: true
  set_verbose: true

general_settings:
  master_key: ${LITELLM_MASTER_KEY}
